### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by ehsan69h** [fingerpich/jalali-moment#61]
I tested 1398-02-30 and it is invalid in [demo](https://fingerpich.github.io/jalali-moment/) page or [jalali-angular-datepicker](https://github.com/fingerpich/jalali-angular-datepicker) component.

**Comment by fingerpich** [comment]
Thanks
Please create a PR if you can fix the problem.

**Comment by pouyamiralayi** [comment]
Hi! is there any update regarding this issue and especially [this one](https://github.com/fingerpich/jalali-moment/issues/60)?
thanks.

**Comment by fingerpich** [comment]
But it doesn't work correctly even in the demo.
Have you tried ..../02/30 and ..../06/31?

**Comment by pouyamiralayi** [comment]
Hi @fingerpich ! i just tested **31/6/1398** and it showed me ``2019/09/22`` which is ok to me.
i think we must compensate the gap _by adding some to minutes or hours_ i guess. for instance my use case was only date with times set to ``00:00:00`` i think i have to add to hours and minutes some value to fill in the gaps. but i am not sure the exact amount of hours! is this because of the daylight saving nature of iran utc?
thanks.

**Comment by fingerpich** [comment]
demo has fixed. [PR](https://github.com/fingerpich/jalali-moment/pull/94/commits/406ad8be4f052cf65332ebd2207faee395d3fde6)

**Comment by fingerpich** [comment]
> Hi @fingerpich ! i just tested **31/6/1398** and it showed me `2019/09/22` which is ok to me.
> i think we must compensate the gap _by adding some to minutes or hours_ i guess. for instance my use case was only date with times set to `00:00:00` i think i have to add to hours and minutes some value to fill in the gaps. but i am not sure the exact amount of hours! is this because of the daylight saving nature of iran utc?
> thanks.

please check the #93
